version: '3.3'
services:
  wizbl:
    build: ./docker/wizbl
    tty: true
    volumes:
      - ./docker/wizbl/config/wizbl_tempcoincore.conf:/root/.wizbl_tempcoincore/wizbl_tempcoincore.conf
      - ./docker/var/data/wizbl:/root/.wizbl_tempcoincore/testnet3
    ports:
      - "18724:18724"
